DROP TABLE BOOKMARK;


--GEN_HIST_NO SEQUENCE **추가
CREATE SEQUENCE SEQ_GEN_HIST_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;


CREATE TABLE FEED (  
    FEED_INDEX NUMBER CONSTRAINT FEED_INDEX_PK PRIMARY KEY, 
    FEED_DATE DATE DEFAULT SYSDATE NOT NULL,  
    FEED_TITLE VARCHAR2(60) NOT NULL,--제목
    FEED_CNT VARCHAR2(1500) NOT NULL,--내용
    FEED_EVAL NUMBER  NOT NULL ,--별점 (타입숫자맞는지?)
    FEED_TIME_RQRD NUMBER NOT NULL , -- 소요시간 (ERD 는 NULL인데 NOT NULL로...) 
    FEED_PUBLIC_TYPE CHAR(20)  DEFAULT '전체' NOT NULL CONSTRAINT FEED_PUBLIC_TYPE_CK CHECK(FEED_PUBLIC_TYPE IN('전체','친구','비공개')) , -- 피드공개여부
    FEED_PAHT_NY CHAR(1)  DEFAULT 'N' NOT NULL CONSTRAINT FEED_PAHT_NY_CK CHECK(FEED_PAHT_NY IN('Y','N')), --경로등록여부
    FEED_RPR_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT FEED_RPR_NY_CK CHECK(FEED_RPR_NY IN('Y','N')), --신고여부
    FEED_RPR_DATE DATE , --신고시간
    FEED_GPX VARCHAR2(300) NOT NULL, --경로파일  (ERD 는 NULL인데 NOT NULL로...)
    FEED_DST NUMBER  NOT NULL ,-- 경로길이(ERD 는 NULL인데 NOT NULL로...) 
    FEED_DEL_NY CHAR(1)  DEFAULT 'N' NOT NULL CONSTRAINT FEED_DEL_NY_CK CHECK(FEED_DEL_NY IN('Y','N')),--피드삭제여부
    MEM_ID VARCHAR(255) NOT NULL REFERENCES MEMBER  --포린키 작성자아이디
);



INSERT INTO FEED VALUES(SEQ_FEED_INDEX.NEXTVAL, SYSDATE, '오늘 뛴 호수공원 코스 추천합니다','뷰도 좋고 사람도 많지 않아서 좋네요',5,6000,'전체','Y','N',null,'경로파일',213,'N','Qdfca12');
INSERT INTO FEED VALUES(SEQ_FEED_INDEX.NEXTVAL, SYSDATE, '오늘의 기록','안양천,30분',4,4000,'친구','Y','N',null,'경로파일',1234,'N','wSDF23');
INSERT INTO FEED VALUES(SEQ_FEED_INDEX.NEXTVAL, SYSDATE, '2023/02/05 달리기 ','1시간 달렸는데 개빡셌다. 페이스조절해야지 ',3.5 ,6000,'친구','N','N',null,'경로파일',2345,'N','cvxzv34');
INSERT INTO FEED VALUES(SEQ_FEED_INDEX.NEXTVAL, DEFAULT, '2021 안양공원 달리기 코스 ','날씨가 춥긴 춥다',3,5400,'비공개','N','N',null,'경로파일',5678,'N','vdfety1111');
INSERT INTO FEED VALUES(SEQ_FEED_INDEX.NEXTVAL, SYSDATE, '한강달리기는 옳다','갓생사는기분',5,6500,DEFAULT,'Y','N',null,'경로파일',1111,DEFAULT,'wSDF23');



CREATE TABLE FEED_COMMENTS(
    FEED_CMN_NO NUMBER PRIMARY KEY,
    FEED_CMN_ID VARCHAR2(15) NOT NULL,
    FEED_CMN_DATE DATE NOT NULL,
    FEED_CMN_CNT VARCHAR2(300) NOT NULL,
    FEED_CMN_RPR CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT FEED_CMN_RPR_CK CHECK(FEED_CMN_RPR IN ('N','Y')),
    FEED_CMN_RPR_DATE DATE,
    FEED_CMN_DEL_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT FEED_CMN_DEL_NY CHECK(FEED_CMN_DEL_NY IN ('N','Y')),
    FEED_INDEX NUMBER NOT NULL REFERENCES FEED
);


INSERT INTO FEED_COMMENTS VALUES(SEQ_FEED_CMN_NO.NEXTVAL,'qwerty8912',SYSDATE,'뛰고 나면 기분이 좋아지는 것 같아요 ㅎㅎ', DEFAULT, SYSDATE, 'Y', 5);
INSERT INTO FEED_COMMENTS VALUES(SEQ_FEED_CMN_NO.NEXTVAL,'holyhs364',SYSDATE,'집 근처인데 한 번 뛰어봐야겠네요~', DEFAULT, SYSDATE, DEFAULT, 1);
INSERT INTO FEED_COMMENTS VALUES(SEQ_FEED_CMN_NO.NEXTVAL,'ohjopo0009',SYSDATE,'저도 내일은 꼭 달리러 나가야겠어요!', DEFAULT, SYSDATE, 'Y', 5);
INSERT INTO FEED_COMMENTS VALUES(SEQ_FEED_CMN_NO.NEXTVAL,'followme7777',SYSDATE,'겨우 이걸로 힘들다니..ㅋㅋ', 'Y', SYSDATE, DEFAULT, 2);
INSERT INTO FEED_COMMENTS VALUES(SEQ_FEED_CMN_NO.NEXTVAL,'rogen0',SYSDATE,'저도 맨날 페이스 조절 실패하는데...ㅋㅋㅋ', 'N', SYSDATE, DEFAULT, 3);






CREATE TABLE GENERAL_HISTORY (  --게시글 히스토리
    GEN_HIST_CTG CHAR(10) CONSTRAINT GEN_HIST_CTG CHECK(GEN_HIST_CTG IN ('피드', '대회','일반')) , --알람객체분류
    GEN_HIST_NO NUMBER NOT NULL , --알람 객체 고유번호(시퀀스생성)
    GEN_HIST_RPR_NY CHAR(1) DEFAULT'N' NOT NULL CONSTRAINT GEN_HIST_RPR_NY_CK CHECK(GEN_HIST_RPR_NY IN('Y','N')),--신고여부
    GEN_HIST_DATE DATE DEFAULT SYSDATE NOT NULL -- 신고들어온시간
);


--게시물 히스토리 INSERT문 
INSERT INTO GENERAL_HISTORY VALUES ('피드', SEQ_GEN_HIST_NO.NEXTVAL,'Y',SYSDATE);
INSERT INTO GENERAL_HISTORY VALUES ('대회', SEQ_GEN_HIST_NO.NEXTVAL,'Y',SYSDATE);
INSERT INTO GENERAL_HISTORY VALUES ('일반', SEQ_GEN_HIST_NO.NEXTVAL,'Y',SYSDATE);
INSERT INTO GENERAL_HISTORY VALUES ('피드', SEQ_GEN_HIST_NO.NEXTVAL,'Y',SYSDATE);
INSERT INTO GENERAL_HISTORY VALUES ('피드', SEQ_GEN_HIST_NO.NEXTVAL,'Y',SYSDATE);


--댓글히스토리 테이블
CREATE TABLE CMN_HISTORY (
    CMN_HIST_CTG VARCHAR2(9) NOT NULL CONSTRAINT CMN_HIST_CTG_CK CHECK(CMN_HIST_CTG IN ('피드', '일반')),
    CMN_HIST_NO NUMBER NOT NULL,
    CMN_HIST_RPR_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT CMN_HIST_RPR_NY_CK CHECK(CMN_HIST_RPR_NY IN ('Y', 'N')),
    CMN_HIST_NEW_NY CHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT CMN_HIST_NEW_NY_CK CHECK(CMN_HIST_NEW_NY IN ('Y','N')),
    CMN_HIST_NICK_NY CHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT CMN_HIST_NICK_NY_CK CHECK(CMN_HIST_NICK_NY IN ('Y', 'N')),
    CMN_HIST_DATE DATE DEFAULT SYSDATE NOT NULL
);

--댓글히스토리 인서트
INSERT INTO CMN_HISTORY VALUES('피드', SEQ_CMN_HIST_NO.NEXTVAL, 'N', 'N', 'N', SYSDATE);
INSERT INTO CMN_HISTORY VALUES('피드', SEQ_CMN_HIST_NO.NEXTVAL, 'Y', 'Y', 'N', '22/01/23');
INSERT INTO CMN_HISTORY VALUES('일반', SEQ_CMN_HIST_NO.NEXTVAL, 'N', 'N', 'N', SYSDATE);
INSERT INTO CMN_HISTORY VALUES('피드', SEQ_CMN_HIST_NO.NEXTVAL, 'N', 'Y', 'N', '22/02/04');
INSERT INTO CMN_HISTORY VALUES('일반', SEQ_CMN_HIST_NO.NEXTVAL, 'Y', 'N', 'Y', '23/01/10');




--찜히스토리 테이블
CREATE TABLE BK_HISTORY(
    FEED_INDEX NUMBER NOT NULL REFERENCES FEED , --피드번호(피드테이블이랑 FK)
     MEM_ID VARCHAR(255) NOT NULL REFERENCES MEMBER, -- 찜행위유저 (멤버테이블이랑 FK)
    BK_HIST_DATE DATE DEFAULT SYSDATE --알림시간
);


--찜히스토리 INSERT문
INSERT INTO BK_HISTORY VALUES (1, 'wSDF23',SYSDATE);
INSERT INTO BK_HISTORY VALUES (2, 'cvxzv34',SYSDATE);
INSERT INTO BK_HISTORY VALUES (3, 'vdfety1111',SYSDATE);
INSERT INTO BK_HISTORY VALUES (4, 'Qdfca12',SYSDATE);
INSERT INTO BK_HISTORY VALUES (5, 'Qdfca12',SYSDATE);




CREATE TABLE BOOKMARK ( --찜테이블
    BK_NO NUMBER NOT NULL CONSTRAINT BK_NO_FK REFERENCES FEED(FEED_INDEX) ON DELETE CASCADE,
    BK_ID VARCHAR2(15) NOT NULL CONSTRAINT BK_ID_FK REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE,
    BK_DATE DATE DEFAULT SYSDATE,
    BK_FOLLOEE_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT BK_FOLLOEE_NY_CK CHECK(BK_FOLLOEE_NY IN ('Y', 'N'))
);



--찜테이블 인서트
INSERT INTO BOOKMARK VALUES(5, 'cvxzv34', DEFAULT, DEFAULT);
INSERT INTO BOOKMARK VALUES(5, 'Qdfca12', DEFAULT, 'Y');
INSERT INTO BOOKMARK VALUES(4, 'wSDF23', DEFAULT, 'Y');
INSERT INTO BOOKMARK VALUES(1, 'wSDF23', DEFAULT, DEFAULT);
INSERT INTO BOOKMARK VALUES(3, 'wSDF23', DEFAULT, 'Y');


COMMENT ON COLUMN BOOKMARK.BK_NO IS '피드번호';   
COMMENT ON COLUMN BOOKMARK.BK_ID IS '회원아이디';
COMMENT ON COLUMN BOOKMARK.BK_DATE IS '찜날짜';
COMMENT ON COLUMN BOOKMARK.BK_FOLLOEE_NY IS '팔로잉여부';
