DROP TABLE FOLLOW;

CREATE TABLE FOLLOW (
	FLW_CUT_NY CHAR(1) DEFAULT 'N' CONSTRAINT FLW_CUT_NY_CK CHECK(FLW_CUT_NY IN ('Y', 'N')) NOT NULL,
    MEM_ID VARCHAR2(20) NOT NULL CONSTRAINT MEM_ID_FK REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE,
    FLW_ED_NY VARCHAR2(20) NOT NULL CONSTRAINT FLW_ED_NY_FK REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE
);
COMMENT ON COLUMN FOLLOW.MEM_ID IS '아이디';   
COMMENT ON COLUMN FOLLOW.FLW_ED_NY IS '다른회원아이디';
COMMENT ON COLUMN FOLLOW.FLW_CUT_NY IS '차단여부';

