--CREATE USER OVCOS IDENTIFIED BY OVCOS;
--GRANT CONNECT, RESOURCE TO OVCOS;

DROP TABLE CHLG_COMMENTS; -- 자식테이블 먼저 삭제
DROP TABLE CHALLENGE;
DROP TABLE CONTEST;
DROP TABLE MEMBER;
DROP TABLE WITHDRAWAL;
DROP TABLE NOTICE;

CREATE TABLE MEMBER (
	MEM_ID VARCHAR2(20) CONSTRAINT MEM_ID_PK PRIMARY KEY,
	MEM_PWD	VARCHAR2(20) NOT NULL,
	MEM_NAME VARCHAR2(15) NOT NULL,
	MEM_NICK VARCHAR2(24) NOT NULL,
	MEM_INTRO VARCHAR2(300),
	MEM_BIRTH DATE,
	MEM_ADMIN_NY CHAR(10) DEFAULT '일반' NOT NULL CONSTRAINT MEM_ADMIN_NY_CK CHECK(MEM_ADMIN_NY IN('일반','관리자')),
	MEM_STATUS VARCHAR2(12) DEFAULT '회원' NOT NULL CONSTRAINT MEM_STATUS_CK CHECK(MEM_STATUS IN('회원','탈퇴','휴먼','일시정지')),
	MEM_LOC_INFO VARCHAR(200),
	MEM_PUBLIC_NY CHAR(1) DEFAULT 'Y' CONSTRAINT MEM_PUBLIC_NY_CK CHECK(MEM_PUBLIC_NY IN('Y','N')),
	MEM_GOAL_DTN NUMBER DEFAULT 0,
	MEM_CODE_NY	VARCHAR2(20),
	MEM_RPR_CUM	NUMBER DEFAULT 0 NOT NULL,
	MEM_API_TYPE VARCHAR2(30) CONSTRAINT MEM_API_TYPE_CK CHECK(MEM_API_TYPE IN('일반','카카오','네이버','구글')),
	MEM_API_TOKEN VARCHAR2(50),
	MEM_EML	VARCHAR2(100) NOT NULL
);

CREATE TABLE CONTEST (
    CNTS_NO NUMBER CONSTRAINT CNTS_NO_PK PRIMARY KEY,
    CNTS_NAME VARCHAR2(60) NOT NULL,
    CNTS_DATE DATE NOT NULL,
    CNTS_URL VARCHAR2(100) NOT NULL
);

CREATE TABLE CHALLENGE (
    CHLG_NO NUMBER CONSTRAINT CHLG_NO_PK PRIMARY KEY, -- 데이터 삽입할때 시퀀스로 값 인가
	CHLG_CTG VARCHAR2(9) CONSTRAINT CHLG_CTG_CK CHECK(CHLG_CTG IN('대회','일반')),
	CHLG_TITLE VARCHAR2(60) NOT NULL,
	CHLG_ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL, -- 데이터 삽입이 이뤄질때 시간
	CHLG_DATE DATE NOT NULL,
	CHLG_ENTER_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT CHLG_ENTER_NY_CK CHECK(CHLG_ENTER_NY IN('N','Y')), -- 참가가능여부?
	CHLG_LOCATION VARCHAR2(15) NOT NULL CONSTRAINT CHLG_LOCATION_CK CHECK(CHLG_LOCATION IN('서울','부산','대구','인천','광주','대전','울산','세종','경기','강원','충북','충남','전북','전남','경북','경남','제주')),
	CHLG_MAX NUMBER NOT NULL,
    CHLG_RPR_ID VARCHAR2(20) CONSTRAINT CHLG_RPR_ID_FK REFERENCES MEMBER(MEM_ID),
	CHLG_RPR_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT CHLG_RPR_NY_CK CHECK(CHLG_RPR_NY IN('N','Y')),
    CHLG_RPR_DATE DATE,
    MATCH_CNTS_NO NUMBER CONSTRAINT MATCH_CNTS_NO_FK REFERENCES CONTEST(CNTS_NO) ON DELETE CASCADE, -- 대회일때만 받음
    MATCH_CHLG_ID VARCHAR2(20) NOT NULL CONSTRAINT MATCH_CHLG_ID_FK REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE
);

CREATE TABLE CHLG_COMMENTS (
    CHLG_CMN_NO NUMBER CONSTRAINT CHLG_CMN_NO_PK PRIMARY KEY, -- 데이터 삽입할때 시퀀스로 값 인가
    CHLG_CMN_DATE DATE DEFAULT SYSDATE NOT NULL,
    CHLG_CMN_CNT VARCHAR2(1500) NOT NULL,
    CHLG_CMN_RPR_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT CHLG_CMN_RPR_NY_CK CHECK(CHLG_CMN_RPR_NY IN('N','Y')),
    CHLG_CMN_RPR_DATE DATE,
    CHLG_CMN_DEL_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT CHLG_CMN_DEL_NY_CK CHECK(CHLG_CMN_DEL_NY IN('N','Y')),
    CHLG_CMN_ID VARCHAR2(20) NOT NULL CONSTRAINT CHLG_CMN_ID_FK REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE,
    CHLG_CMN_RPR_ID VARCHAR2(20) CONSTRAINT CHLG_CMN_RPR_ID_FK REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE, -- 미신고의 경우 NULL일 수 있음
    MATCH_CHLG_NO NUMBER NOT NULL CONSTRAINT MATCH_CHLG_NO_FK REFERENCES CHALLENGE(CHLG_NO) ON DELETE CASCADE
);

CREATE TABLE WITHDRAWAL (
    WTH_NO NUMBER NOT NULL CONSTRAINT WTH_NO_CK CHECK(WTH_NO IN(1,2,3,4)), -- JS에서 기본값 1번 설정, 탈퇴한 경우에만 데이터가 추가되므로 NULL인 경우 미존재함.
    WTH_RSN VARCHAR2(150), -- WITH_NO이 4(기타)인 경우에만 탈퇴사유가 작성되므로 NULL 가능
    WTH_DATE DATE DEFAULT SYSDATE NOT NULL,
    WTH_ID VARCHAR2(20) NOT NULL CONSTRAINT WTH_ID_FK REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE
);

CREATE TABLE NOTICE (
    NTC_NO NUMBER NOT NULL,
    NTC_TITLE VARCHAR2(90) NOT NULL,
    NTC_CNT VARCHAR2(4000) NOT NULL,
    NTC_DATE DATE DEFAULT SYSDATE NOT NULL,
    NTC_COUNT NUMBER DEFAULT 0 NOT NULL
);


COMMENT ON COLUMN CHALLENGE.CHLG_NO IS '챌린지번호';
COMMENT ON COLUMN CHALLENGE.CHLG_CTG IS '대회/일반';
COMMENT ON COLUMN CHALLENGE.CHLG_TITLE IS '챌린지명';
COMMENT ON COLUMN CHALLENGE.CHLG_ENROLL_DATE IS '등록일자';
COMMENT ON COLUMN CHALLENGE.CHLG_DATE IS '모이는시간';
COMMENT ON COLUMN CHALLENGE.CHLG_ENTER_NY IS '참가여부';
COMMENT ON COLUMN CHALLENGE.MATCH_CNTS_NO IS '연결된대회번호';
COMMENT ON COLUMN CHALLENGE.CHLG_LOCATION IS '지역선택';
COMMENT ON COLUMN CHALLENGE.CHLG_MAX IS '최대참여인원';
COMMENT ON COLUMN CHALLENGE.CHLG_RPR_ID IS '신고자아이디';
COMMENT ON COLUMN CHALLENGE.CHLG_RPR_NY IS '신고여부';
COMMENT ON COLUMN CHALLENGE.CHLG_RPR_DATE IS '신고시간';
COMMENT ON COLUMN CHALLENGE.MATCH_CHLG_ID IS '등록자아이디';

COMMENT ON COLUMN CHLG_COMMENTS.CHLG_CMN_NO IS '댓글번호';
COMMENT ON COLUMN CHLG_COMMENTS.CHLG_CMN_ID IS '작성자아이디';
COMMENT ON COLUMN CHLG_COMMENTS.CHLG_CMN_DATE IS '작성일자';
COMMENT ON COLUMN CHLG_COMMENTS.CHLG_CMN_CNT IS '내용';
COMMENT ON COLUMN CHLG_COMMENTS.CHLG_CMN_RPR_ID IS '신고자아이디';
COMMENT ON COLUMN CHLG_COMMENTS.CHLG_CMN_RPR_NY IS '신고여부';
COMMENT ON COLUMN CHLG_COMMENTS.CHLG_CMN_RPR_DATE IS '신고시간';
COMMENT ON COLUMN CHLG_COMMENTS.CHLG_CMN_DEL_NY IS '댓글삭제여부';
COMMENT ON COLUMN CHLG_COMMENTS.MATCH_CHLG_NO IS '연결된챌린지번호';

COMMENT ON COLUMN CONTEST.CNTS_NO IS '대회번호';
COMMENT ON COLUMN CONTEST.CNTS_NAME IS '대회명';
COMMENT ON COLUMN CONTEST.CNTS_DATE IS '대회날짜';
COMMENT ON COLUMN CONTEST.CNTS_URL IS '대회사이트주소';

COMMENT ON COLUMN WITHDRAWAL.WTH_NO IS '탈퇴사유';
COMMENT ON COLUMN WITHDRAWAL.WTH_RSN IS '기타입력란';
COMMENT ON COLUMN WITHDRAWAL.WTH_DATE IS '탈퇴일자';
COMMENT ON COLUMN WITHDRAWAL.WTH_ID IS '회원아이디';

COMMENT ON COLUMN NOTICE.NTC_NO IS '공지번호';
COMMENT ON COLUMN NOTICE.NTC_TITLE IS '공지제목';
COMMENT ON COLUMN NOTICE.NTC_CNT IS '공지내용';
COMMENT ON COLUMN NOTICE.NTC_DATE IS '공지등록일';
COMMENT ON COLUMN NOTICE.NTC_COUNT IS '조회수';


