DROP TABLE FEED;
DROP TABLE FEED_COMMENTS;

CREATE TABLE FEED ( 
    FEED_INDEX NUMBER CONSTRAINT FEED_INDEX_PK PRIMARY KEY, --피드번호
    FEED_DATE DATE DEFAULT SYSDATE NOT NULL,  -- 작성일 
    FEED_TITLE VARCHAR2(60) NOT NULL,--제목
    FEED_CNT VARCHAR2(1500) NOT NULL,--내용
    FEED_EVAL NUMBER  NOT NULL ,--별점 (타입숫자맞는지?)
    FEED_TIME_RQRD NUMBER NOT NULL , -- 소요시간 (ERD 는 NULL인데 NOT NULL로...) 
    FEED_PUBLIC_TYPE CHAR(20)  DEFAULT '전체' NOT NULL CONSTRAINT FEED_PUBLIC_TYPE_CK CHECK(FEED_PUBLIC_TYPE IN('전체','친구','비공개')) , -- 피드공개여부
    FEED_PAHT_NY CHAR(1)  DEFAULT 'N' NOT NULL CONSTRAINT FEED_PAHT_NY_CK CHECK(FEED_PAHT_NY IN('Y','N')), --경로등록여부
    FEED_RPR_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT FEED_RPR_NY_CK CHECK(FEED_RPR_NY IN('Y','N')), --신고여부
    FEED_RPR_DATE DATE , --신고시간
    FEED_GPX VARCHAR2(300) NOT NULL, --경로파일  (ERD 는 NULL인데 NOT NULL로...)
    FEED_DST NUMBER  NOT NULL ,-- 경로길이(ERD 는 NULL인데 NOT NULL로...) 
    FEED_DEL_NY CHAR(1)  DEFAULT 'N' NOT NULL CONSTRAINT FEED_DEL_NY_CK CHECK(FEED_DEL_NY IN('Y','N')),--피드삭제여부
    MEM_ID VARCHAR(255) NOT NULL REFERENCES MEMBER  --포린키 작성자아이디
);


COMMENT ON COLUMN FEED.FEED_INDEX IS '피드번호';
COMMENT ON COLUMN FEED.FEED_DATE IS '작성일자';
COMMENT ON COLUMN FEED.FEED_TITLE IS '피드제목';
COMMENT ON COLUMN FEED.FEED_CNT IS '피드내용';
COMMENT ON COLUMN FEED.FEED_EVAL IS '별점';
COMMENT ON COLUMN FEED.FEED_TIME_RQRD IS '소요시간';
COMMENT ON COLUMN FEED.FEED_PUBLIC_TYPE IS '피드 공개여부';
COMMENT ON COLUMN FEED.FEED_PAHT_NY IS '경로등록여부';
COMMENT ON COLUMN FEED.FEED_RPR_NY IS '피드신고여부';
COMMENT ON COLUMN FEED.FEED_RPR_DATE IS '피드신고시간';
COMMENT ON COLUMN FEED.FEED_GPX IS '경로파일';
COMMENT ON COLUMN FEED.FEED_DST IS '경로길이';
COMMENT ON COLUMN FEED.FEED_DEL_NY IS '피드삭제여부';
COMMENT ON COLUMN FEED.MEM_ID IS '회원 아이디';



CREATE SEQUENCE SEQ_FEED_INDEX
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;



CREATE TABLE FEED_COMMENTS(
    FEED_CMN_NO NUMBER PRIMARY KEY,
    FEED_CMN_ID VARCHAR2(15) NOT NULL,
    FEED_CMN_DATE DATE NOT NULL,
    FEED_CMN_CNT VARCHAR2(300) NOT NULL,
    FEED_CMN_RPR CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT FEED_CMN_RPR_CK CHECK(FEED_CMN_RPR IN ('N','Y')),
    FEED_CMN_RPR_DATE DATE,
    FEED_CMN_DEL_NY CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT FEED_CMN_DEL_NY CHECK(FEED_CMN_DEL_NY IN ('N','Y')),
    FEED_INDEX NUMBER NOT NULL REFERENCES FEED
);

COMMENT ON COLUMN FEED_COMMENTS.FEED_CMN_NO IS '댓글 인덱스';
COMMENT ON COLUMN FEED_COMMENTS.FEED_CMN_ID IS '댓글 작성자 아이디';
COMMENT ON COLUMN FEED_COMMENTS.FEED_CMN_DATE IS '댓글 작성일자';
COMMENT ON COLUMN FEED_COMMENTS.FEED_CMN_CNT IS '댓글 내용';
COMMENT ON COLUMN FEED_COMMENTS.FEED_CMN_RPR IS '댓글 신고 여부';
COMMENT ON COLUMN FEED_COMMENTS.FEED_CMN_RPR_DATE IS '댓글 신고 시간';
COMMENT ON COLUMN FEED_COMMENTS.FEED_CMN_DEL_NY IS '댓글 삭제 여부';
COMMENT ON COLUMN FEED_COMMENTS.FEED_INDEX IS '피드 번호';

CREATE SEQUENCE SEQ_FEED_CMN_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

